# -*- coding: utf-8 -*-
"""modulpenjumlahan.pynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ncI5w0SorkRAgPjeyKqKWFARkuPuNdhC
"""

def penjumlahan(angka_1,angka_2):
  jumlah = angka_1 + angka_2
  return jumlah